// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.migration.version", 172);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1785841795);
user_pref("browser.search.region", "PK");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[]},\"seen\":[\"reset-pbm-toolbar-button\"],\"dirtyAreaCache\":[],\"currentVersion\":24,\"newElementCount\":0}");
user_pref("datareporting.dau.cachedUsageProfileGroupID", "4546db90-a419-4f90-b267-d9f07886453b");
user_pref("datareporting.dau.cachedUsageProfileID", "1e7b6d2e-644a-461f-827e-77942e05766c");
user_pref("distribution.fedora.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "152.0.6");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260714143900");
user_pref("extensions.lastAppVersion", "152.0.6");
user_pref("extensions.lastPlatformVersion", "152.0.6");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"data-leak-blocker@mozilla.com\":\"6fa677e9-a08b-4baa-ae0a-197f71177122\",\"formautofill@mozilla.org\":\"c3ae9967-e5a1-4cc9-b753-060fe65cbe6e\",\"ipp-activator@mozilla.com\":\"518df167-fc59-4a19-88c1-20187b9e3de1\",\"pictureinpicture@mozilla.org\":\"ad42819d-dc8a-47c4-8e9c-cae989ba4318\",\"addons-search-detection@mozilla.com\":\"30abe7ee-bdc8-4b07-bb25-e894b043afe6\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"0d7670db-0322-4760-b971-77d9c17872d0\",\"default-theme@mozilla.org\":\"3d3715fc-0472-4919-a175-06a487f3c73d\"}");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.profileId", "5c52c4d7-0162-4943-b01e-10c200437ab9");
user_pref("pdfjs.enabledCache.state", true);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("toolkit.profiles.newProfileSubmitted", true);
user_pref("toolkit.startup.last_success", 1785841819);
user_pref("toolkit.telemetry.cachedClientID", "849ea87a-76a0-4d1b-adb5-9cab50214028");
user_pref("toolkit.telemetry.cachedProfileGroupID", "0c619109-5682-4771-94de-b3c87a2b20a1");
user_pref("toolkit.telemetry.previousBuildID", "20260714143900");
